In [1]:
import cv2
from keras.models import load_model
import numpy as np
model = load_model('keras_model.h5')
cap = cv2.VideoCapture(0)
data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)

while True: 
    ret, frame = cap.read()
    resized_frame = cv2.resize(frame, (224, 224), interpolation = cv2.INTER_AREA)
    image_np = np.array(resized_frame)
    normalized_image = (image_np.astype(np.float32) / 127.0) - 1 # Normalize the image
    data[0] = normalized_image
    prediction = model.predict(data)
    cv2.imshow('frame', frame)
    # Press q to close the window
    print(prediction)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
            
# After the loop release the cap object
cap.release()
# Destroy all the windows
cv2.destroyAllWindows()

2022-01-25 20:38:38.935620: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/pete/miniconda3/envs/RockPaperScissors/lib/python3.9/site-packages/cv2/../../lib64:
2022-01-25 20:38:38.935634: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2022-01-25 20:38:39.627116: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:939] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-01-25 20:38:39.627299: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/pete/miniconda3/envs/RockPaper

[[1.6389007e-05 2.1383634e-07 1.4713594e-04 9.9983621e-01]]
[[1.0858398e-05 2.9519984e-07 1.2357630e-04 9.9986529e-01]]
[[2.7304854e-05 2.9343877e-07 2.7416047e-04 9.9969828e-01]]
[[1.9302099e-06 5.0093579e-08 2.0881974e-04 9.9978918e-01]]
[[2.5365812e-06 1.8469866e-08 1.7119525e-04 9.9982625e-01]]
[[3.0507310e-06 3.6336107e-08 4.4579970e-04 9.9955112e-01]]
[[6.5977988e-06 1.2629731e-07 6.5935153e-04 9.9933392e-01]]
[[2.8816848e-06 2.1745771e-08 3.4616282e-04 9.9965096e-01]]
[[6.0941575e-06 8.3627498e-08 4.9283210e-04 9.9950099e-01]]
[[6.1131223e-06 8.6385207e-08 3.5928591e-04 9.9963450e-01]]
[[4.4949388e-06 1.7394571e-08 1.6540910e-04 9.9983001e-01]]
[[3.0585165e-06 7.2526760e-08 2.6786403e-04 9.9972898e-01]]
[[2.8786899e-06 9.2646587e-08 3.5973915e-04 9.9963725e-01]]
[[9.8509952e-07 3.7046430e-09 1.2268710e-04 9.9987626e-01]]
[[2.6784753e-06 3.0459343e-08 1.8016026e-04 9.9981719e-01]]
[[1.2916388e-06 5.8549450e-09 3.9436304e-04 9.9960440e-01]]
[[2.4430224e-07 1.3873371e-08 2.5379215e